Framerate=function(a){this.numFramerates=10;this.framerateUpdateInterval=500;this.callback=a;this.renderTime=-1;this.framerates=[];var e=this;setInterval(function(){e.updateFramerate()},this.framerateUpdateInterval)};Framerate.prototype.updateFramerate=function(){for(var a=0,e=0;e<this.framerates.length;++e)a+=this.framerates[e];a/=this.framerates.length;a=Math.round(a);this.callback&&this.callback("Framerate:"+a+"fps")};
Framerate.prototype.snapshot=function(){if(this.renderTime<0)this.renderTime=(new Date).getTime();else{var a=(new Date).getTime();for(this.framerates.push(1E3/(a-this.renderTime));this.framerates.length>this.numFramerates;)this.framerates.shift();this.renderTime=a}};CanvasMatrix4=function(a){if(typeof a=="object")if("length"in a&&a.length>=16){window.status="yup";this.load(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8],a[9],a[10],a[11],a[12],a[13],a[14],a[15]);return}else if(a instanceof CanvasMatrix4){this.load(a);return}this.makeIdentity()};
CanvasMatrix4.prototype.multVector=function(a,e){var d=a[0],c=a[1],f=a[2],e=e||[];e[0]=d*this.m11+c*this.m21+f*this.m31+1*this.m41;e[1]=d*this.m12+c*this.m22+f*this.m32+1*this.m42;e[2]=d*this.m13+c*this.m23+f*this.m33+1*this.m43;e[3]=d*this.m14+c*this.m24+f*this.m34+1*this.m44;return e};
CanvasMatrix4.prototype.load=function(a){if(a&&typeof a=="object"){if(a instanceof CanvasMatrix4){this.m11=a.m11;this.m12=a.m12;this.m13=a.m13;this.m14=a.m14;this.m21=a.m21;this.m22=a.m22;this.m23=a.m23;this.m24=a.m24;this.m31=a.m31;this.m32=a.m32;this.m33=a.m33;this.m34=a.m34;this.m41=a.m41;this.m42=a.m42;this.m43=a.m43;this.m44=a.m44;return}if("length"in a&&a.length==16){this.m11=a[0];this.m12=a[1];this.m13=a[2];this.m14=a[3];this.m21=a[4];this.m22=a[5];this.m23=a[6];this.m24=a[7];this.m31=a[8];
this.m32=a[9];this.m33=a[10];this.m34=a[11];this.m41=a[12];this.m42=a[13];this.m43=a[14];this.m44=a[15];return}}this.makeIdentity()};CanvasMatrix4.prototype.getAsArray=function(){return[this.m11,this.m12,this.m13,this.m14,this.m21,this.m22,this.m23,this.m24,this.m31,this.m32,this.m33,this.m34,this.m41,this.m42,this.m43,this.m44]};
CanvasMatrix4.prototype.getAsWebGLFloatArray=function(){return new Float32Array([this.m11,this.m12,this.m13,this.m14,this.m21,this.m22,this.m23,this.m24,this.m31,this.m32,this.m33,this.m34,this.m41,this.m42,this.m43,this.m44])};CanvasMatrix4.prototype.makeIdentity=function(){this.m11=1;this.m21=this.m14=this.m13=this.m12=0;this.m22=1;this.m32=this.m31=this.m24=this.m23=0;this.m33=1;this.m43=this.m42=this.m41=this.m34=0;this.m44=1};
CanvasMatrix4.prototype.transpose=function(){var a=this.m12;this.m12=this.m21;this.m21=a;a=this.m13;this.m13=this.m31;this.m31=a;a=this.m14;this.m14=this.m41;this.m41=a;a=this.m23;this.m23=this.m32;this.m32=a;a=this.m24;this.m24=this.m42;this.m42=a;a=this.m34;this.m34=this.m43;this.m43=a};
CanvasMatrix4.prototype.invert=function(){var a=this._determinant4x4();if(Math.abs(a)<1.0E-8)return null;this._makeAdjoint();this.m11/=a;this.m12/=a;this.m13/=a;this.m14/=a;this.m21/=a;this.m22/=a;this.m23/=a;this.m24/=a;this.m31/=a;this.m32/=a;this.m33/=a;this.m34/=a;this.m41/=a;this.m42/=a;this.m43/=a;this.m44/=a};CanvasMatrix4.prototype.translateOpt=function(a,e,d){this.m41=a||0;this.m42=e||0;this.m43=d||0};
CanvasMatrix4.prototype.translate=function(a,e,d){var c=new CanvasMatrix4;c.m41=a||0;c.m42=e||0;c.m43=d||0;this.multRight(c)};CanvasMatrix4.prototype.scale=function(a,e,d){a==void 0&&(a=1);d==void 0?d=e==void 0?e=a:1:e==void 0&&(e=a);var c=new CanvasMatrix4;c.m11=a;c.m22=e;c.m33=d;this.multRight(c)};CanvasMatrix4.prototype.sin=Math.sin;CanvasMatrix4.prototype.cos=Math.cos;
CanvasMatrix4.prototype.rotateX=function(a){a*=0.5;var e=this.sin(a),a=this.cos(a),d=e*e;this.m22=1-2*d;this.m23=2*e*a;this.m32=-2*e*a;this.m33=1-2*d;return this};CanvasMatrix4.prototype.rotateY=function(a){a*=0.5;var e=this.sin(a),a=this.cos(a),d=e*e;this.m11=1-2*d;this.m13=-2*e*a;this.m31=2*e*a;this.m33=1-2*d;return this};CanvasMatrix4.prototype.rotateZ=function(a){a*=0.5;var e=this.sin(a),a=this.cos(a),d=e*e;this.m11=1-2*d;this.m12=2*e*a;this.m21=-2*e*a;this.m22=1-2*d;return this};
CanvasMatrix4.prototype.rotate=function(a,e,d,c){a/=2;var f=Math.sin(a),a=Math.cos(a),g=f*f,b=Math.sqrt(e*e+d*d+c*c);b==0?(d=e=0,c=1):b!=1&&(e/=b,d/=b,c/=b);b=new CanvasMatrix4;if(e==1&&d==0&&c==0)b.m11=1,b.m12=0,b.m13=0,b.m21=0,b.m22=1-2*g,b.m23=2*f*a,b.m31=0,b.m32=-2*f*a,b.m33=1-2*g;else if(e==0&&d==1&&c==0)b.m11=1-2*g,b.m12=0,b.m13=-2*f*a,b.m21=0,b.m22=1,b.m23=0,b.m31=2*f*a,b.m32=0,b.m33=1-2*g;else if(e==0&&d==0&&c==1)b.m11=1-2*g,b.m12=2*f*a,b.m13=0,b.m21=-2*f*a,b.m22=1-2*g,b.m23=0,b.m31=0,b.m32=
0,b.m33=1;else{var j=e*e,k=d*d,h=c*c;b.m11=1-2*(k+h)*g;b.m12=2*(e*d*g+c*f*a);b.m13=2*(e*c*g-d*f*a);b.m21=2*(d*e*g-c*f*a);b.m22=1-2*(h+j)*g;b.m23=2*(d*c*g+e*f*a);b.m31=2*(c*e*g+d*f*a);b.m32=2*(c*d*g-e*f*a);b.m33=1-2*(j+k)*g}b.m14=b.m24=b.m34=0;b.m41=b.m42=b.m43=0;b.m44=1;this.multRight(b)};
CanvasMatrix4.prototype.multRight=function(a){var e=this.m11*a.m12+this.m12*a.m22+this.m13*a.m32+this.m14*a.m42,d=this.m11*a.m13+this.m12*a.m23+this.m13*a.m33+this.m14*a.m43,c=this.m11*a.m14+this.m12*a.m24+this.m13*a.m34+this.m14*a.m44,f=this.m21*a.m11+this.m22*a.m21+this.m23*a.m31+this.m24*a.m41,g=this.m21*a.m12+this.m22*a.m22+this.m23*a.m32+this.m24*a.m42,b=this.m21*a.m13+this.m22*a.m23+this.m23*a.m33+this.m24*a.m43,j=this.m21*a.m14+this.m22*a.m24+this.m23*a.m34+this.m24*a.m44,k=this.m31*a.m11+
this.m32*a.m21+this.m33*a.m31+this.m34*a.m41,h=this.m31*a.m12+this.m32*a.m22+this.m33*a.m32+this.m34*a.m42,m=this.m31*a.m13+this.m32*a.m23+this.m33*a.m33+this.m34*a.m43,n=this.m31*a.m14+this.m32*a.m24+this.m33*a.m34+this.m34*a.m44,o=this.m41*a.m11+this.m42*a.m21+this.m43*a.m31+this.m44*a.m41,p=this.m41*a.m12+this.m42*a.m22+this.m43*a.m32+this.m44*a.m42,q=this.m41*a.m13+this.m42*a.m23+this.m43*a.m33+this.m44*a.m43,r=this.m41*a.m14+this.m42*a.m24+this.m43*a.m34+this.m44*a.m44;this.m11=this.m11*a.m11+
this.m12*a.m21+this.m13*a.m31+this.m14*a.m41;this.m12=e;this.m13=d;this.m14=c;this.m21=f;this.m22=g;this.m23=b;this.m24=j;this.m31=k;this.m32=h;this.m33=m;this.m34=n;this.m41=o;this.m42=p;this.m43=q;this.m44=r};
CanvasMatrix4.prototype.multLeft=function(a){var e=this.m11,d=this.m12,c=this.m13,f=this.m14,g=this.m21,b=this.m22,j=this.m23,k=this.m24,h=this.m31,m=this.m32,n=this.m33,o=this.m34,p=this.m41,q=this.m42,r=this.m43,u=this.m44,l=a.m11,v=a.m12,w=a.m13,i=a.m14,y=a.m21,t=a.m22,x=a.m23,s=a.m24,z=a.m31,A=a.m32,B=a.m33,C=a.m34,D=a.m41,E=a.m42,F=a.m43,a=a.m44;this.m11=l*e+v*g+w*h+i*p;this.m12=l*d+v*b+w*m+i*q;this.m13=l*c+v*j+w*n+i*r;this.m14=l*f+v*k+w*o+i*u;this.m21=y*e+t*g+x*h+s*p;this.m22=y*d+t*b+x*m+s*
q;this.m23=y*c+t*j+x*n+s*r;this.m24=y*f+t*k+x*o+s*u;this.m31=z*e+A*g+B*h+C*p;this.m32=z*d+A*b+B*m+C*q;this.m33=z*c+A*j+B*n+C*r;this.m34=z*f+A*k+B*o+C*u;this.m41=D*e+E*g+F*h+a*p;this.m42=D*d+E*b+F*m+a*q;this.m43=D*c+E*j+F*n+a*r;this.m44=D*f+E*k+F*o+a*u;return this};
CanvasMatrix4.prototype.ortho=function(a,e,d,c,f,g){var b=(a+e)/(a-e),j=(c+d)/(c-d),k=(g+f)/(g-f),h=new CanvasMatrix4;h.m11=2/(a-e);h.m12=0;h.m13=0;h.m14=0;h.m21=0;h.m22=2/(c-d);h.m23=0;h.m24=0;h.m31=0;h.m32=0;h.m33=-2/(g-f);h.m34=0;h.m41=b;h.m42=j;h.m43=k;h.m44=1;this.multRight(h)};
CanvasMatrix4.prototype.frustum=function(a,e,d,c,f,g){var b=new CanvasMatrix4;b.m11=2*f/(e-a);b.m12=0;b.m13=0;b.m14=0;b.m21=0;b.m22=2*f/(c-d);b.m23=0;b.m24=0;b.m31=(e+a)/(e-a);b.m32=(c+d)/(c-d);b.m33=-(g+f)/(g-f);b.m34=-1;b.m41=0;b.m42=0;b.m43=-(2*g*f)/(g-f);b.m44=0;this.multRight(b)};CanvasMatrix4.prototype.perspective=function(a,e,d,c){var a=Math.tan(a*Math.PI/360)*d,f=-a;this.frustum(e*f,e*a,f,a,d,c)};
CanvasMatrix4.prototype.lookat=function(a,e,d,c,f,g,b,j,k){var h=new CanvasMatrix4,c=a-c,f=e-f,g=d-g,m=Math.sqrt(c*c+f*f+g*g);m&&(c/=m,f/=m,g/=m);var n=j*g-k*f,o=-b*g+k*c,p=b*f-j*c,j=-c*p+g*n,b=c*o-f*n;if(m=Math.sqrt(n*n+o*o+p*p))n/=m,o/=m,p/=m;if(m=Math.sqrt(b*b+j*j+k*k))b/=m,j/=m,k/=m;h.m11=n;h.m12=o;h.m13=p;h.m14=0;h.m21=b;h.m22=j;h.m23=k;h.m24=0;h.m31=c;h.m32=f;h.m33=g;h.m34=0;h.m41=0;h.m42=0;h.m43=0;h.m44=1;h.translate(-a,-e,-d);this.multRight(h)};
CanvasMatrix4.prototype._determinant2x2=function(a,e,d,c){return a*c-e*d};CanvasMatrix4.prototype._determinant3x3=function(a,e,d,c,f,g,b,j,k){return a*this._determinant2x2(f,g,j,k)-c*this._determinant2x2(e,d,j,k)+b*this._determinant2x2(e,d,f,g)};
CanvasMatrix4.prototype._determinant4x4=function(){var a=this.m12,e=this.m13,d=this.m14,c=this.m21,f=this.m22,g=this.m23,b=this.m24,j=this.m31,k=this.m32,h=this.m33,m=this.m34,n=this.m41,o=this.m42,p=this.m43,q=this.m44;return this.m11*this._determinant3x3(f,k,o,g,h,p,b,m,q)-a*this._determinant3x3(c,j,n,g,h,p,b,m,q)+e*this._determinant3x3(c,j,n,f,k,o,b,m,q)-d*this._determinant3x3(c,j,n,f,k,o,g,h,p)};
CanvasMatrix4.prototype._makeAdjoint=function(){var a=this.m11,e=this.m12,d=this.m13,c=this.m14,f=this.m21,g=this.m22,b=this.m23,j=this.m24,k=this.m31,h=this.m32,m=this.m33,n=this.m34,o=this.m41,p=this.m42,q=this.m43,r=this.m44;this.m11=this._determinant3x3(g,h,p,b,m,q,j,n,r);this.m21=-this._determinant3x3(f,k,o,b,m,q,j,n,r);this.m31=this._determinant3x3(f,k,o,g,h,p,j,n,r);this.m41=-this._determinant3x3(f,k,o,g,h,p,b,m,q);this.m12=-this._determinant3x3(e,h,p,d,m,q,c,n,r);this.m22=this._determinant3x3(a,
k,o,d,m,q,c,n,r);this.m32=-this._determinant3x3(a,k,o,e,h,p,c,n,r);this.m42=this._determinant3x3(a,k,o,e,h,p,d,m,q);this.m13=this._determinant3x3(e,g,p,d,b,q,c,j,r);this.m23=-this._determinant3x3(a,f,o,d,b,q,c,j,r);this.m33=this._determinant3x3(a,f,o,e,g,p,c,j,r);this.m43=-this._determinant3x3(a,f,o,e,g,p,d,b,q);this.m14=-this._determinant3x3(e,g,h,d,b,m,c,j,n);this.m24=this._determinant3x3(a,f,k,d,b,m,c,j,n);this.m34=-this._determinant3x3(a,f,k,e,g,h,c,j,n);this.m44=this._determinant3x3(a,f,k,e,
g,h,d,b,m)};var j5=function(){var a,e,d=function(){var a=CanvasMatrix4;return function(){var b=new a;b.lookat(0,0,5,0,0,0,0,1,0);b.perspective(45,1,1,1E3);return b.getAsWebGLFloatArray()}}(),c=function(a,b){return function(){function e(a,u){var i=b.getElementById(u);if(!i)return null;for(var d="",c=i.firstChild;c;)c.nodeType===3&&(d+=c.textContent),c=c.nextSibling;if(i.type==="x-shader/x-fragment")i=a.createShader(a.FRAGMENT_SHADER);else if(i.type==="x-shader/x-vertex")i=a.createShader(a.VERTEX_SHADER);else return null;
a.shaderSource(i,d);a.compileShader(i);return!a.getShaderParameter(i,a.COMPILE_STATUS)?(console.error("Error compiling shader\n",a.getShaderInfoLog(i)),null):i}function c(b,i){var b=b||"vBasic",i=i||"fAlphaTexture",d=b+"+"+i;if(s[d])return s[d];var l=e(a,i),f=e(a,b);if(!l||!f)return console.error("missing shader "+d),null;var t=a.createProgram();a.attachShader(t,f);a.attachShader(t,l);a.linkProgram(t);if(!a.getProgramParameter(t,a.LINK_STATUS))return console.error("LINK_STATUS error"),null;l={program:t,
meta:g(t)};t={program:t,meta:g(t)};s[d]=t;h||(h=l);return l}var i={},d=function(b){switch(b){case a.FLOAT_MAT4:return 16;case a.FLOAT_MAT3:return 9;case a.FLOAT_MAT2:return 4;case a.FLOAT_VEC4:case a.INT_VEC4:case a.BOOL_VEC4:return 4;case a.FLOAT_VEC3:case a.INT_VEC3:case a.BOOL_VEC3:return 3;case a.FLOAT_VEC2:case a.INT_VEC2:case a.BOOL_VEC2:return 2;default:return 1}},f=function(b){switch(b){case a.FLOAT_MAT4:case a.FLOAT_MAT3:case a.FLOAT_MAT2:case a.FLOAT_VEC4:case a.FLOAT_VEC2:case a.FLOAT_VEC3:return a.FLOAT;
case a.INT_VEC4:case a.INT_VEC3:case a.INT_VEC2:return a.INT;case a.BOOL_VEC4:case a.BOOL_VEC3:case a.BOOL_VEC2:return a.BOOL;default:return b}};i[a.FIXED]=a.uniform1i;i[a.SHORT]=a.uniform1i;i[a.UNSIGNED_BYTE]=a.uniform1i;i[a.BYTE]=a.uniform1i;i[a.INT]=a.uniform1i;i[a.UNSIGNED_INT]=a.uniform1i;i[a.FLOAT]=a.uniform1f;i[a.SAMPLER_2D]=a.uniform1i;i[a.FLOAT_MAT4]=a.uniformMatrix4fv;i[a.FLOAT_MAT3]=a.uniformMatrix3fv;i[a.FLOAT_MAT2]=a.uniformMatrix2fv;i[a.FLOAT_VEC2]=a.uniform2fv;i[a.FLOAT_VEC3]=a.uniform3fv;
i[a.FLOAT_VEC4]=a.uniform4fv;i[a.INT_VEC2]=a.uniform2iv;i[a.INT_VEC3]=a.uniform3iv;i[a.INT_VEC4]=a.uniform4iv;i[a.BOOL]=a.uniform1i;i[a.BOOL_VEC2]=a.uniform2iv;i[a.BOOL_VEC3]=a.uniform3iv;i[a.BOOL_VEC4]=a.uniform4iv;var h=null,s={},g=function(b){var e={uniforms:[],uniform:{},attribute:{}},c=[],l;for(l in a)c.push(l);var c=c.sort(),h={};c.forEach(function(b){h[a[b]]=b});l=0;for(var g=a.getProgramParameter(b,a.ACTIVE_UNIFORMS),s;l<g;){c=a.getActiveUniform(b,l);s=a.getUniformLocation(b,c.name);e.uniforms.push(c.name);
var v=e.uniform,j=c.name,w=c.name,k=c.type,x=h[c.type],m=c.type===a.SAMPLER_2D,n;a:switch(c.type){case a.FLOAT_MAT4:case a.FLOAT_MAT3:case a.FLOAT_MAT2:n=!0;break a;default:n=!1}v[j]={name:w,glType:k,type:x,isTexture:m,isMatrixType:n,length:d(c.type),idx:l,location:s,setter:i[c.type],locVal:[s,!1]};l++}g=a.getProgramParameter(b,a.ACTIVE_ATTRIBUTES);for(l=0;l<g;)c=a.getActiveAttrib(b,l),e.attribute[c.name]={name:c.name,glType:c.type,glBaseType:f(c.type),type:h[c.type],length:d(c.type),idx:l,location:a.getAttribLocation(b,
c.name)},l++;return e};return function(a,b){var e=c(a,b)||h,i={alpha:1},l={};e.meta.uniforms.forEach(function(a){var b=e.meta.uniform[a],c=b.length,a=b.name;Object.defineProperty(l,"$"+b.name,{get:function(){return i[a]},set:function(b){if(b&&b.length!==c)b.length=c;i[a]=b}})});l.setAttribute=function(a,b,c,l){if(b=e.meta.attribute[b])a.enableVertexAttribArray(b.location),a.vertexAttribPointer(b.location,b.length,b.glBaseType,!1,c,l)};l.update=function(a){var b=e.meta,c=b.uniform,b=b.uniforms,l,u,
d=b.length;a.currentShaderProgram=e;a.useProgram(e.program);for(var f=0;d--;)l=b[d],u=i[l],l=c[l],u!==void 0&&u!==null&&(l.isTexture?(a.activeTexture(a["TEXTURE"+f]),a.bindTexture(a.TEXTURE_2D,u),l.locVal[1]=f++):l.isMatrixType?l.locVal[2]=u:l.locVal[1]=u,l.setter.apply(a,l.locVal))};l.$getShaderProgram=function(){return e.program};return l}}(a)},f=function(a,b,c,e){var i=a.createBuffer();a.bindBuffer(b,i);a.bufferData(b,c,a.STATIC_DRAW);i.itemSize=e;i.numItems=c.length/e;return i},g=function(a,c,
e){var d=a.createTexture();d.image=new Image;d.image.onload=function(){b(a,d,d.image);e&&e(d);e=null;d.image.src="data:image/png;,"};d.image.src=c},b=function(a,b,c){a.bindTexture(a.TEXTURE_2D,b);a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!0);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,c);c=null;a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR_MIPMAP_NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);
a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.generateMipmap(a.TEXTURE_2D);b.destory=function(){a.deleteTexture(b);c=b=null};a.bindTexture(a.TEXTURE_2D,null);return b},j={},k=0,h=0,m=function(a){k=a.offsetX/750;h=a.offsetY/750;if(r.onMouseMove)r.onMouseMove(k,h)},n=function(a,b,c,e,i){for(var d=b.length,i=i||0,f=0,h=[0,0,0,1],g=[];i<d;i+=e){for(f=0;f<c;f++)h[f]=b[i+f];a.multVector(h,g);for(f=0;f<c;f++)b[i+f]=g[f]}return b},o=function(b,c,e,d){var i=new CanvasMatrix4,b=q(b,c,e,d),
h=[],g=[],c=function(a,b,c){h=h.concat(n(b,a.vertices.concat(),3,5,0));g=g.concat(a.indices.map(function(a){return c*4+a}));console.log(g)};c(b,i,0);i.translate(0,0,-1);c(b,i,1);i.makeIdentity();i.rotate(Math.PI*0.5,0,1,0);c(b,i,2);i.makeIdentity();i.rotate(Math.PI*0.5,-1,0,0);c(b,i,3);i.makeIdentity();i.rotate(Math.PI*0.5,0,1,0);i.translate(1,0,0);c(b,i,4);i.makeIdentity();i.rotate(Math.PI*0.5,-1,0,0);i.translate(0,1,0);c(b,i,5);return{vertices:f(a,a.ARRAY_BUFFER,new Float32Array(h),5),indices:f(a,
a.ELEMENT_ARRAY_BUFFER,new Uint16Array(g),1),size:g.length}},p=function(b,c,e,d){b=q(b,c,e,d);return{vertices:f(a,a.ARRAY_BUFFER,new Float32Array(b.vertices),5),indices:f(a,a.ELEMENT_ARRAY_BUFFER,new Uint16Array(b.indices),1),size:b.indices.length}},q=function(a,b,c,e){var d,f,h=[],g=[],s=[],j=s.size=0;for(f=0;f<a+1;f++){h[f]=[];for(d=0;d<b+1;d++)h[f][d]=s.size,s[j++]=f*c,s[j++]=d*e,s[j++]=0,s[j++]=f/a,s[j++]=d/b,s.size++}var c=0,k,m;for(f=0;f<a;f++)for(d=0;d<b;d++)e=h[f][d],j=h[f+1][d],k=h[f][d+
1],m=h[f+1][d+1],g[c+0]=e,g[c+1]=j,g[c+2]=m,g[c+3]=e,g[c+4]=m,g[c+5]=k,c+=6;return{vertices:s,indices:g}},r={offset:function(){var a=CanvasMatrix4,b=new a,c=new a,e=new a,d=new a,f=new a,h=new a,g=new a;return function(a){a.parent?g.load(a.parent):g.makeIdentity();if(a.x||a.y||a.z)b.translateOpt(a.x,a.y,a.z),g.multLeft(b);if(a.originX||a.originY||a.originX)h.translateOpt(a.originX,a.originY,a.originZ),g.multLeft(h);if(a.scaleX!==void 0||a.scaleY!==void 0||a.scaleZ!==void 0)c.makeIdentity(),c.scale(a.scaleX===
void 0?1:a.scaleX,a.scaleY===void 0?1:a.scaleY,a.scaleZ===void 0?1:a.scaleZ),g.multLeft(c);a.rotateX&&g.multLeft(e.rotateX(a.rotateX));a.rotateY&&g.multLeft(d.rotateY(a.rotateY));a.rotateZ&&g.multLeft(f.rotateZ(a.rotateZ));if(a.originX||a.originY||a.originX)h.translateOpt(-a.originX,-a.originY,-a.originZ),g.multLeft(h);return g.getAsWebGLFloatArray()}}(),camera:d,attachCanvas:function(b){var d,f=["webgl","experimental-webgl","moz-webgl","webkit-3d"],g;for(g=0;f.length>g;g++)try{if(d=b.getContext(f[g]))break}catch(h){}!d&&
console.error("Could not initialise WebGL");d=a=d;d.viewport(0,0,750,750);d.clearColor(0,0,0,1);d.clearDepth(3);d.enable(d.DEPTH_TEST);d.mvMatrix=new CanvasMatrix4;d.mvMatrix.makeIdentity();d.mvMatrix2=new CanvasMatrix4;d.mvMatrix2.makeIdentity();d.mvMatrix.translate(-21,11.5,-23);d.perspectiveMatrix=new CanvasMatrix4;d.perspectiveMatrix.makeIdentity();d.perspectiveMatrix.lookat(0,0.5,5,0,0,0,0,1,0);d.perspectiveMatrix.perspective(45,1,0.1,1E3);d.perspectiveMatrixArray=d.perspectiveMatrix.getAsWebGLFloatArray();
d.enable(d.BLEND);d.blendFuncSeparate(d.SRC_ALPHA,d.ONE_MINUS_SRC_ALPHA,d.SRC_ALPHA,d.ONE);d.clear(d.COLOR_BUFFER_BIT);e=c(a,document);b.addEventListener("mousemove",m,!1);r.gl=a},texture:function(b,c){g(a,b,c)},shader:function(){return e()},quad:function(b,c,d,e,f){var e=f=f||1,d=d||1,c=c||1,b="quad,"+[c,d,e,f],g=j[b]=j[b]||p(c,d,e,f);return{draw:function(b,c,d){if(c)b.$uMVMatrix=c;b.$uPMatrix=d||a.perspectiveMatrixArray;a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,g.indices);a.bindBuffer(a.ARRAY_BUFFER,
g.vertices);b.setAttribute(a,"aTextureCoord",20,12);b.setAttribute(a,"aVertexPosition",20,0);b.update(a,c);a.drawElements(a.TRIANGLES,g.size,a.UNSIGNED_SHORT,0)}}},cube:function(b,c,d,e,f){var e=f=f||1,d=d||1,c=c||1,b="quad,"+[c,d,e,f],g=j[b]=j[b]||o(c,d,e,f);return{draw:function(b,c,d){if(c)b.$uMVMatrix=c;b.$uPMatrix=d||a.perspectiveMatrixArray;a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,g.indices);a.bindBuffer(a.ARRAY_BUFFER,g.vertices);b.setAttribute(a,"aTextureCoord",20,12);b.setAttribute(a,"aVertexPosition",
20,0);b.update(a,c);a.drawElements(a.TRIANGLES,g.size,a.UNSIGNED_SHORT,0)}}}};Object.defineProperty(r,"mouseX",{get:function(){return k}});Object.defineProperty(r,"mouseY",{get:function(){return h}});return r}();
